#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompactCalendarView.Resource", IsApplication=false)]

namespace CompactCalendarView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int compactCalendarBackgroundColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int compactCalendarCurrentDayBackgroundColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int compactCalendarCurrentSelectedDayBackgroundColor = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int compactCalendarTargetHeight = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int compactCalendarTextColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int compactCalendarTextSize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CompactCalendarView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int CompactCalendarView_compactCalendarBackgroundColor = 1;
			
			// aapt resource value: 2
			public static int CompactCalendarView_compactCalendarCurrentDayBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int CompactCalendarView_compactCalendarCurrentSelectedDayBackgroundColor = 3;
			
			// aapt resource value: 5
			public static int CompactCalendarView_compactCalendarTargetHeight = 5;
			
			// aapt resource value: 4
			public static int CompactCalendarView_compactCalendarTextColor = 4;
			
			// aapt resource value: 0
			public static int CompactCalendarView_compactCalendarTextSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
